// Generated by CoffeeScript 1.7.1

/*
 *
 *BackboneModel
 *
 */
var VideoModel, VideoView;

VideoModel = Backbone.Model;

window.VideoCollection = Backbone.Collection.extend({
  model: VideoModel,
  url: "/videos"
});

VideoView = Backbone.View.extend({
  initialize: function(model) {
    this.render();
    return this.model.on('change:name', (function(_this) {
      return function(mod, name) {
        return _this.$el.text(name);
      };
    })(this));
  },
  className: 'item',
  tagName: 'li',
  render: function() {
    this.$el.text(this.model.get('name'));
    return this;
  }
});

window.AppView = Backbone.View.extend({
  initialize: function(videos) {
    return this.listenTo(this.collection, 'add', this.render);
  },
  el: '#videos',
  render: function(model) {
    var view;
    view = new VideoView({
      model: model
    });
    return this.$el.append(view.$el);
  }
});
