// Generated by CoffeeScript 1.7.1

/*
 *
 *BackboneModel
 *
 */
var VideoModel, VideoView;

VideoModel = Backbone.Model;

window.VideoCollection = Backbone.Collection.extend({
  model: VideoModel,
  url: "/videos"
});

VideoView = Backbone.View.extend({
  className: 'item',
  render: function() {
    return "<li>" + (this.model.get('name')) + "</li>";
  }
});

window.AppView = Backbone.View.extend({
  initialize: function(videos) {
    return this.listenTo(this.collection, 'add', this.render);
  },
  el: '#videos',
  render: function(model) {
    console.log(model.toJSON());
    return this.$el.append(new VideoView({
      model: model
    }).render());
  }
});
